service: dev-customer-wishlist

custom:
  TABLE_NAME: dev-customer-wishlist

provider:
  name: aws
  runtime: nodejs10.x
  environment: ${self:custom}
  region: us-east-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:BatchWriteItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem

      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.TABLE_NAME}"
functions:

  createItem:
    handler: handler.createItem
    description: "Saves the data"
    events:
      - http:
          method: post
          path: create
  deleteDuplicateItem:
    handler: handler.deleteDuplicateItem
    description: "deletes Duplicate"
    events:
      - http:
          method: post
          path: deleteDuplicate

resources:
  Resources:
    GreeterTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.TABLE_NAME}
