Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: uid
          AttributeType: S
        - AttributeName: pid
          AttributeType: S
      KeySchema:
        - AttributeName: uid
          KeyType: HASH
        - AttributeName: pid
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
